import { StyleSheet } from "react-native"

const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 25,
    justifyContent: "center",
    backgroundColor: "#fff",
  },
  title: {
    fontSize: 28,
    fontWeight: "bold",
    color: "#007F7F",
    textAlign: "center",
  },
  subtitle: {
    textAlign: "center",
    color: "#666",
    marginBottom: 30,
  },
  input: {
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: 8,
    padding: 12,
    marginBottom: 15,
  },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  rememberRow: { flexDirection: "row", alignItems: "center" },
  rememberText: { marginLeft: 6 },
  forgot: { color: "#007F7F", fontWeight: "500" },
  button: {
    backgroundColor: "#007F7F",
    padding: 14,
    borderRadius: 10,
    marginTop: 25,
  },
  buttonText: {
    color: "#fff",
    textAlign: "center",
    fontWeight: "bold",
    fontSize: 16,
  },
  googleButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: 8,
    padding: 12,
    marginBottom: 10,
  },
  appleButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#000",
    borderRadius: 8,
    padding: 12,
  },
  icon: { width: 20, height: 20, marginRight: 8 },
  footer: { flexDirection: "row", justifyContent: "center", marginTop: 30 },
  signupLink: { color: "#007F7F", fontWeight: "bold" },
  overlay: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.4)",
  },
  card: {
    width: 300,
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 25,
    alignItems: "center",
    shadowColor: "#000",
    shadowOpacity: 0.15,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 10,
    elevation: 6,
  },
  iconWrapper: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: "#E6F7F7",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 10,
  },
  iconEmoji: { fontSize: 38 },
  successTitle: {
    fontSize: 18,
    fontWeight: "600",
    textAlign: "center",
    color: "#007F7F",
  },
  successSubtitle: {
    fontSize: 15,
    color: "#555",
    textAlign: "center",
    marginTop: 8,
    marginBottom: 20,
  },
  successButton: {
    backgroundColor: "#007F7F",
    borderRadius: 10,
    paddingVertical: 12,
    paddingHorizontal: 25,
  },
  successButtonText: { color: "#fff", fontWeight: "600", fontSize: 16 },
})

export default styles
